### ISSUE TITLE
password shouldn't be divulged in source code

### ISSUE THREAD

**Issue by dckc** [ibesoft11/rchain-dbr-graphql#2]
https://github.com/ibesoft11/graphql/blob/658a47c21bed87c7f36b7bd50c25f3e24e5745dc/db.js#L6

**Comment by ibesoft11** [comment]
I missed that @dckc, I have fixed it now...

**Comment by dckc** [comment]
fixed in 64f32693743f5f3d24f4d2e3bb40e21ed1ef3bad
