### ISSUE TITLE
dataface_* tables should not be exported

### ISSUE THREAD

**Issue by dckc** [ibesoft11/rchain-dbr-graphql#3]
I don't see any reason to export these tables.

https://github.com/ibesoft11/graphql/blob/658a47c21bed87c7f36b7bd50c25f3e24e5745dc/schemaResolver.js#L30

**Comment by ibesoft11** [comment]
Ok, I'll remove the queries for dataface_* tables, Thanks.

**Comment by dckc** [comment]
fixed in 240aceaf0c4cfb008d0eff9a3a845f9f783fc56d
