### ISSUE TITLE
createIssue conflicts with use of issue table as a cache

### ISSUE THREAD

**Issue by dckc** [ibesoft11/rchain-dbr-graphql#4]
The `issue` table is just a cache of data from github. Unless this `createIssue` mutation is going to push the change all the way to github, it makes no sense.

https://github.com/ibesoft11/graphql/blob/658a47c21bed87c7f36b7bd50c25f3e24e5745dc/schemaResolver.js#L30

**Comment by ibesoft11** [comment]
If I understand you, should I remove the createIssue mutation  ?
And again, I feel not every table needs to have mutations... It'll be better if I am given a list of the tables that need mutations.

**Comment by dckc** [comment]
As I discussed with @jimscarver, I don't expect any mutations to come in via graphql:

  - you'd have to update the history tables to0
  - authentication would be essential
    - I'd have to review all the details of how it's done, and that doesn't get us any closer to where we want to be, which is running on RChain

**Comment by ibesoft11** [comment]
Could you please explain the kind of authentication we are talking about ?

**Comment by dckc** [comment]
We have to ensure that only votes by coop members are counted.

Currently we use OAuth from github and discord: https://github.com/rchain/bounties/issues/413

**Comment by ibesoft11** [comment]
Ok, but I don't think the authentication would be done on this GraphQL server since we are not doing any mutations ? Only queries to existing data.

**Comment by dckc** [comment]
It would be more clear that we're not doing any mutations if the `createIssue` code were gone. :)

**Comment by ibesoft11** [comment]
Yeah, I'll remove it (and every other mutation)...

**Comment by dckc** [comment]
fixed in d2d57b3f2fa97af44d2da14afde40d2d7d02c995
