### ISSUE TITLE
BIGINT is overkill for rating

### ISSUE THREAD

**Issue by dckc** [ibesoft11/rchain-dbr-graphql#5]
rating is  is 1, 2, or 3

https://github.com/ibesoft11/graphql/blob/658a47c21bed87c7f36b7bd50c25f3e24e5745dc/schemaResolver.js#L30

**Comment by ibesoft11** [comment]
Noted. Changed to TINYINT...

**Comment by dckc** [comment]
fixed in 9f38dca6f3ff1cde1745c2a9933a944c1550311a
